// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// Do provides a mock function with given fields: message, url, headers
func (_m *Requester) Do(message interface{}, url string, headers http.Header) ([]byte, *http.Response, error) {
	ret := _m.Called(message, url, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(interface{}, string, http.Header) []byte); ok {
		r0 = rf(message, url, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(interface{}, string, http.Header) *http.Response); ok {
		r1 = rf(message, url, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(interface{}, string, http.Header) error); ok {
		r2 = rf(message, url, headers)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
