linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - ineffassign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
run:
  go: '1.17'
  skip-dirs:
    - res
