project_name: GoMail
# Hooks to run before build
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make all
# Zip
archives:
  - builds:
      - main
    format: zip
    name_template: "{{ tolower .ProjectName }}_v{{ .Version }}"
    wrap_in_directory: "insights-proxy"
    files:
      - README.md
      - LICENCE
      - .env.example
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
release:
  github:
    owner: ainsleyclark
    name: go-mail
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: true
