language: go

go:
  - 1.16

branches:
  only:
    - main

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t .
  - go get -u github.com/haya14busa/goverage
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0

script:
  - go fmt ./...
  - golangci-lint run ./...
  - go clean -testcache && go test -race $(go list ./... | grep -v tests)
  - goverage -v -coverprofile=c.out ./
  - goveralls -coverprofile=c.out -service travis-ci

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    git config credential.helper "store --file=.git/credentials";
    echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials;
    go install;
    go-tag;
    fi