// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mailgun "github.com/mailgun/mailgun-go/v4"

	mock "github.com/stretchr/testify/mock"
)

// mailGunSendFunc is an autogenerated mock type for the mailGunSendFunc type
type mailGunSendFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, message
func (_m *mailGunSendFunc) Execute(ctx context.Context, message *mailgun.Message) (string, string, error) {
	ret := _m.Called(ctx, message)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *mailgun.Message) string); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, *mailgun.Message) string); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *mailgun.Message) error); ok {
		r2 = rf(ctx, message)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
