// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mail "github.com/sendgrid/sendgrid-go/helpers/mail"
	mock "github.com/stretchr/testify/mock"

	rest "github.com/sendgrid/rest"
)

// sendGridSendFunc is an autogenerated mock type for the sendGridSendFunc type
type sendGridSendFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: email
func (_m *sendGridSendFunc) Execute(email *mail.SGMailV3) (*rest.Response, error) {
	ret := _m.Called(email)

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(*mail.SGMailV3) *rest.Response); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*mail.SGMailV3) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
