// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gosparkpost "github.com/SparkPost/gosparkpost"
	mock "github.com/stretchr/testify/mock"
)

// sparkSendFunc is an autogenerated mock type for the sparkSendFunc type
type sparkSendFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: t
func (_m *sparkSendFunc) Execute(t *gosparkpost.Transmission) (string, *gosparkpost.Response, error) {
	ret := _m.Called(t)

	var r0 string
	if rf, ok := ret.Get(0).(func(*gosparkpost.Transmission) string); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *gosparkpost.Response
	if rf, ok := ret.Get(1).(func(*gosparkpost.Transmission) *gosparkpost.Response); ok {
		r1 = rf(t)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gosparkpost.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*gosparkpost.Transmission) error); ok {
		r2 = rf(t)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
