name: Email

on:
  push:
    branches: [ main, deps ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 1 1,15 * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: TestEnv
        run: printenv

#      - name: Test
#        run: make test

